In [1]:
from kafka import KafkaProducer
import json
import time
import csv
import string

In [2]:
def json_serializer(data):
    return json.dumps(data).encode("utf-8")

producer  = KafkaProducer(bootstrap_servers = ["kafka:9093"],
                          value_serializer=json_serializer)

In [3]:
import pandas as pd
data = pd.re

AttributeError: module 'pandas' has no attribute 're'

In [11]:
with open('/opt/data.csv', newline='\n') as csvFile:
    spamreader = csv.reader(csvFile, delimiter=',')
    count = 0
    for row in spamreader:
        if(count==0):
            count+=1
            continue
        count+=1
        strs = '0,'
        for item in row:
            strs = strs + str(item) + ","
        producer.send("test7", strs)
        if(count%2 ==0):
            time.sleep(0.5)
        if(count == 10000):
            break

KeyboardInterrupt:

In [9]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.1.5-cp37-cp37m-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 8.0 MB/s eta 0:00:01     |█████████▏                      | 2.7 MB 820 kB/s eta 0:00:09
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas) (2.8.1)
Collecting numpy>=1.15.4
  Downloading numpy-1.19.4-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 12.0 MB/s eta 0:00:01    |████████████████████▊           | 9.4 MB 11.4 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Collecting pytz>=2017.2
  Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 11.2 MB/s eta 0:00:01
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.19.4 pandas-1.1.5 pytz-2020.4

In [10]:
import pandas as pd
df = pd.read_csv('/opt/data.csv')
df.

,pktTotalCount,flowStart,octetTotalCount,f_pktTotalCount,f_octetTotalCount,f_flowStart,b_pktTotalCount,b_octetTotalCount,b_flowStart,category,application_protocol,web_service
0,27,1555953515,1254,14,602,1555953515,13,652,1555953515,Web,Unknown,HTTP_Proxy
1,696,1555953515,34384,349,14249,1555953515,347,20135,1555953515,Web,TLS,Google
2,491,1555953515,49295,247,17921,1555953515,244,31374,1555953528,Web,TLS,Amazon
3,27,1555953515,6583,12,1595,1555953515,15,4988,1555953515,Web,Unknown,TLS
4,9,1555953515,705,5,489,1555953515,4,216,1555953515,SocialNetwork,TLS,Facebook
...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,1556143432,92,1,52,1556143432,1,40,1556143432,Unspecified,Unknown,Unknown
1048571,28,1556143432,7900,12,2405,1556143432,16,5495,1556143432,Web,TLS,Google
1048572,2,1556143432,92,1,52,1556143432,1,40,1556143432,Unspecified,Unknown,Unknown
1048573,2,1556143432,170,1,65,1556143432,1,105,1556143432,Web,DNS,Google
1048574,12,1556143432,1310,7,873,1556143432,5,437,1556143432,Web,TLS,Google

In [12]:
type(df["pktTotalCount"][0])

numpy.int64